name: kenlampinen
favicon: null
layout_spectrum: 0.64237
typography_spectrum: 0.4081898
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#a1adb9'
    - '#070f11'
    - '#596f84'
    - '#9e8169'
    - '#e5dcd0'
  brandStrength: 0.5625
  lightness: 0.375
  saturation: 0.75
  rhythmicContrast: 0.5
purpose: []
