name: kenlampinen
favicon: null
layout_spectrum: 0.37749
typography_spectrum: 0.4081898
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#041830'
    - '#0191A3'
    - '#6F6E9B'
    - '#FBFDFF'
    - '#42CFDF'
  brandStrength: 0.384638
  lightness: 0.730715
  saturation: 0.3158606
  rhythmicContrast: 0.4084478
purpose: []
